config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'confirmations'
}
  resources :videos do 
    resources :comments 
  end
  resources :users, only: [:index, :show]
  resources :categories
  resources :landing, only: [:index, :show]
  resources :charges, only: [:new, :create]
  root to: "videos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :videos
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    
  validates :name, length: { minimum: 3 ,maximum: 20}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
  
  
  has_many :videos
  has_many :comments
  has_one_attached :avatar

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_one_attached :clip
  has_one_attached :thumbnail

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     helper_method  :signed_in?, :is_admin?

     def signed_in?
          !!current_user
     end

     def is_admin?
          signed_in? ? current_user.admin : false
     end


     protected
          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar)}
          end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def search
    @categories = Category.where("title LIKE ?", "%" + params[:q] + "%")
  end  

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :image)
  end







  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    @stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_video
before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
before_action :comment_owner, only: [:destroy, :edit, :update]

  def create
    @comment = @video.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to video_path(@video)
    else
      render 'new'
    end

  end

  def destroy
    @comment.destroy
    redirect_to video_path(@video)
  end

  def edit

  end

  def update 
    if @comment.update(params[:comment].permit(:content))
      redirect_to video_path(@video)
    else
      render'edit'
    end
  end


  private

  def find_video
    @video = Video.find(params[:video_id])
  end

  def find_comment
    @comment = @video.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = "Accès refusé, petit malin !"
      redirect_to @video
    end
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    videos_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    #@user_videos = @user.videos
    @user_videos = Video.where(user_id: params[:id]) 
  end

  def index
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  layout "application", only: [:index]

  def index
    @categories = Category.all

    
    cate = params[:cate]     
    if !cate.nil?       
      @videos = Video.where( :category_id => cate)
 
    else  
     @videos = Video.all     
    end   
  end

  def show
    @video = Video.find(params[:id])
    @comments = Comment.where(video_id: @video).order("created_at DESC")
    
  end

  def new
    @video = current_user.videos.build
  end

  def create
    @video = current_user.videos.build(video_params)


    if @video.save
      redirect_to @video
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])

    if @video.update(video_params)
      redirect_to @video
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])

    @video.destroy
    redirect_to videos_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :description, :category_id, :clip, :thumbnail, :user_id)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar(user, size=40 )
    if user.avatar.attached?
      user.avatar.variant(resize: "#{size}x#{size}!")
    else
      gravatar_image_url(user.email, size: size)

    end
  end

end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_categories-form.html.erb
<div class="flex-row d-flex justify-content-center">

<div class="col-md-8">
    <div class="card mt-5">

        <div class="card-body">
        <%= form_for @category do |f| %>

            <div class="form-group">
                <%= f.label :Titre %>
                <%= f.text_field :title %>
                <br></br>
            </div>

            
           
                <%= f.submit " Valider ", class: 'btn btn-outline-primary'%>

            <%= link_to " Retour  ", categories_path, class: 'btn btn-outline-secondary'%>
        
        </div>
        </div>
        <% end %>
    </div>
</div>




<br></br>
<br></br>

app/views/categories/edit.html.erb
<h1>Nouvelle Catégorie</h1>
<p>Find me in app/views/categorys/edit.html.erb</p>
<%= render 'categories-form' %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-10">
    <center>
    <%= link_to "Créer une nouvelle Catégorie", new_category_path, class: 'btn btn-lg btn-success', style: 'font-weight: 400;'%>
    </center>
    <br>
    <% @categories.each do |category| %>
      <div class="card mt-5">
      
        <div class="card-header">
        <center>
          <h5 class="card-title"><%= link_to category.title, category_path(category.id) %></h5>
          <p class="card-text ">On pensera à rajouter une colonne description, c'est promis !</p>
        </center>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-1">
    </div>
  </div>

app/views/categories/new.html.erb
<center><h1>Nouvelle Catégorie</h1>
<h5><i>N'oublie pas de rajouter une image !</i><h5>
<br>
<%= render 'categories-form' %>
</center>

app/views/categories/search.erb
<h1>resultat de la recherche </h1>


<%= render @categories%>

app/views/categories/show.html.erb
<h1>La Catégorie Créer</h1>
<br>

<style>
.my-container {
border: 2px solid rgb(166, 155, 158);
}

.but {
    display:flex;
    flex-direction: row
}

</style>

<div class="container my-container">
    <div class="d-flex justify-content-center">
        <div class="bs-component">
        <br>

            <h3><%= @category.title %></h3>
            <%= image_tag(@category.image, style:'width:100%') if @category.image.attached? %>

            <div class="container but"
                <div class="row">
                    <% if is_admin? %>
                    <%= link_to "Modifier", edit_category_path(@category.id), class: 'btn btn-lg btn-primary'%>
                        <%= link_to "Supprimer", category_path(@category.id), method: :delete, class: 'btn btn-lg btn-danger'%>
                        <%= link_to " Retour  ", categories_path, class: 'btn btn-lg btn-secondary'%>
                    <% end %>
                </div>

            </div>

        </div>    
    </div>
</div>    

<br></br>

app/views/charges/create.html.erb
<br>
<center><h3>Merci, tu as donné <strong>$5.00</strong>!</h3><center>
<br>

app/views/charges/new.html.erb
<div class="jumbotron new-charge-jumbotron">
<p>Faire un don </p>
</div>
<br>

<center>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><h2><b>Donner: 5 €</b></h2></span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Achat d'un produit"
      data-amount="500"
      data-locale="auto">
  </script>
  <% end %>
  </center>

<style>
  .new-charge-jumbotron {
  display: flex;
  background: url(<%= asset_path 'people_together.jpg' %>);
  align-items: center;
  justify-content: center;
  height: 400px;
  background-repeat: no-repeat;
  background-size: 100%;
  width: 100%;
  background-position-y: center;
  color: rgb(133, 130, 132);
  font-weight: 600;
  font-size:100px;
}
</style>

app/views/comments/_comment.html.erb
<h6><%= pluralize(@comments.count, " commentaire") %></h6>


<%= render 'comments/form' %>
<% @comments.each do |comment| %>

  <p>

  
      <b><%= comment.user.name %></b>
      <% if current_user == comment.user or is_admin? %>
          <%= link_to "Supprimer", [comment.video, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary'%>
          <%= link_to "Modifier", edit_video_comment_path(comment.video, comment), class: 'btn btn-sm btn-outline-secondary'%>
      <% end %> 
  </p>

  <ul>
      <li>
      <%= comment.content %>
      </li>
  </ul>


  
<% end %> 

app/views/comments/_form.html.erb
<div class="row">

  <div class="comment_form">
<%= form_for([@video, @video.comments.build]) do |f| %>
   <%= f.text_area :content, class: 'form-control' %> 
   <div class="d-flex justify-content-end">
<%= f.submit "Ajouter un commantaire" , class: 'btn btn-sm btn-outline-secondary'%>
  <% end %>
  </div>
  </div>
 </div>

 

app/views/comments/edit.html.erb
<div class="row">
 <div class="col-6 offset-3">
  <div class="comment_form">
<%= form_for([@video, @comment]) do |f| %>
  <%= f.text_area :content , class:"form-control mb-2"%>
  <div class="col-6 offset-4">
  <%= f.submit "Modifier mon commenaire" , class:'btn btn-sm btn-outline-secondary'%>
    <% end %>
    </div>
  </div>
  </div>
</div>

app/views/landing/show.html.erb
<h1>Landing#show</h1>
<p>Find me in app/views/landing/show.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<body>
<h3>Bienvenue sur ta page de profil, <u><%= @user.name%></u>.</h3>
<center>
<%= link_to 'Modifier mon profil', edit_user_registration_path , class: 'btn btn-sm btn-outline-secondary'%>
</center>
<br><br>
<h3> Voici les contenus que tu as mis en ligne : </h3>


<div class="container categories-container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 ", style="padding-top: 10px;">
        <% @user_videos.each do |video| %>
            <div class="col">
                <div class="card border-secondary mb-3 cards" style="max-width: 20rem;">

            <div class="card-header">
                <center><h4>Titre : <%= video.title %></h4></center>
            </div>

            <div class="card-body">
                <div class="flex-container text">
                        <br>
                        <div style="width:275px; height:200px">
                            <%= video_tag(url_for(video.clip), style:'width:100%') %>
                        </div>
                        

                          <h6><strong>Catégorie : </strong><%= video.category.title %></h6>

                          <h6><strong>Description : </strong><%= video.description %></h6>

                          <h6><strong>Auteur : </strong><%= video.user.name %></h6>
                          
                          
                          <center>
                          <%= link_to "Regarder !", video_path(video.id), class: 'btn btn-sm btn-outline-secondary'%>
                          <%= link_to "Modifier", edit_video_path(video.id), class: 'btn btn-sm btn-outline-secondary'%>
                          </center>
                          
                   
                        </div>
                    </div>
                </div>
            </div> 
            <% end %>
        </div>
    </div>
</div>












</body>


<STYLE>

h1 {
  text-align: center;
  color: black
}

.carousel-inner {
    height: 500px;
}



body{
  text-align: center;
}

 
</STYLE>

app/views/videos/_videos-form.erb
<div class="flex-row d-flex justify-content-center align-items-center">
    <div class="col-md-8">
        <div class="card mt-5">

            <div class="card-body">
            <%= form_for @video do |f| %>

                <div class="form-group">
                    <%= f.label :Titre %>
                    <%= f.text_field :title, class: 'form-control' %>
                </div>

                <br>
                <ul>
                <li>
                <div class="form-group">
                    <%= f.label :Fichier_Mp4 %>
                    <%= f.file_field :clip %>
                </div>
                </li>

                <br>
                <li>
                <div class="form-group">
                    <p>Sélectionner sa catégorie <%= f.select :category_id, Category.all.map {|c| [c.title, c.id]} %></p>
                </div>
                </li>
                </ul>

                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_area :description, class: 'form-control' %> 
                </div>
                <br>

                <center>
                    <%= f.submit " Valider ", class: 'btn btn-success'%>
                <%= link_to " Retour  ", categories_path, class: 'btn btn-secondary'%>
                <center>
            </div>
        </div>
        <% end %>
    </div>
</div>
</div>

app/views/videos/edit.html.erb
<div class="jumbotron edit-video-jumbotron">
<h3 class="centered-text">Editer sa vidéo</h3>
</div>

<%= render 'videos-form' %>

<br><br><br><br>

<style>

.edit-video-jumbotron {
  display: flex;
  background: url(<%= asset_path 'cate-economy.jpg' %>);
  align-items: center;
  justify-content: center;
  height: 300px;
  background-repeat: no-repeat;
  background-size: 100%;
  width: 100%;
  background-position-y: center;
}

.centered-text {
  color: white;
  font-size: 60px;
  font-weight: 900;
  text-decoration:underline;
}

</style>

app/views/videos/index.html.erb
<% if user_signed_in? %>

<center><h2><b>Ca y est !</b> A présent tu peux profiter du contenu, et de la communauté d'<strong><u>Omniscience</u><strong></h2></center>
<center><h4>Tu peux partager ta vidéo et tes connaissances.</h4></center>
<center><h5><i><u>L'administrateur peut supprimer ou modifier n'importe quelle vidéo et rajouter des catégories.</h5></i></center>
<div class="jumbotron index-jumbotron">
<div class="center-div">
<center><%= link_to "Partage ta vidéo !", new_video_path, class: 'btn btn-lg btn-success', style: 'font-weight: 400; font-size:30px; margin-right: 20px;' %>
</div>
</div>



<div class="container-fluid">

    <div class="row">

        <div class="col-md-10">
        
            <div class="row">

            <% @videos.each do |video| %>
                <div class="col-md-3">
                    <div class="card mt-3">

                        <div class="card-header">
                            <center>
                            <h4><%= video.user.name.capitalize %> </h4>
                            </center>
                        </div>

                        <div class="card-body">
                           
                        

                                <%= video_tag(url_for(video.clip), class: "center-img") %>
                      
                    
                      
                        
                    

                        
                        <center>
                        <h5><b>"<%= video.title.capitalize %>"</b></h5>
                        
                        <%= link_to "Regarder !", video_path(video.id), class: 'btn  btn-secondary', style: 'font-weight: 400;'%>
                        </center>
                        
                        </div>





                    </div>
                </div>
            <% end %>
            </div>
        </div>

        <div class="col-md-2">

            <div class="card mt-3">
                <div class="card-header">
                    Catégories
                </div>
                
                <div class="card-body categories-cards">
                    <ul class="list-group">
                
                    <% @categories.each do |category| %> 
                        <button type="button" class="btn btn-secondary mt-2">
                        <b><%= link_to category.title, videos_path(:cate => category.id), style:'color:white'%>
                        <span class="badge badge-light"><%= category.videos.count %></span></b>
                        </button>
                        
        
                <% end %>
                </ul>
                </div>

        </div>
    </div>
</div>
</div>


<% else %>

<div class="contenair welcome-container">
<h1>Bienvenue !</h1>
<h3><u><b>Omniscience</b></u> est un site de streaming à but éducationnel</h3>
<h5>Merci de vous enregistrer. </h5> 
<p> En créant un compte, vous pourrez accéder à notre site.</p>
<%= button_to "Créer un compte", new_user_registration_path, :method => "get", class: 'btn btn-lg btn-success',style: 'font-weight: 400;
font-size:30px;' %> 

</div>
<br>
<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="https://images.unsplash.com/photo-1614899417406-e6f8485cd279?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGtub3dsZWRnZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-center">Connaissance</h5>
      <p class="card-text text-center">Comprendre les enjeux économiques, scientifiques et ou astronomiques avec des vidéos clés en mains qui analyseront pour vous les élémentés clés.</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://images.unsplash.com/photo-1522071901873-411886a10004?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80k" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-center">Accessible à tous</h5>
      <p class="card-text text-center">Les vidéos postées pourront être consultées par toute la communauté et cela gratuitement afin de rendre accessible la voie à la connaissance !</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-center">Communauté</h5>
      <p class="card-text text-center">Notre communauté est notre unique source de savoir, elle est diversifiée et soucieuse de la qualité des contenus postés.</p>
    </div>
  </div>
</div>
<% end %>

<STYLE>

h1 {
  text-align: center;
  color: black
}

.carousel-inner {
    height: 500px;
}

.welcome-container {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  justify-content: space-between;
  flex-direction: column;
  }
  
  .create_button {
    font-weight: 1000;
    font-size:25px;
    background-color: rgb(124, 124, 124);
    border: none;
    color: black;
    padding: 10px 75px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    border-radius: 12px;
    border: 3px solid black;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
  .create_button:hover {
    background-color: white;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
    border: 3px solid black;
  } 
  
  .index-jumbotron {
    display: flex;
    background: url(<%= asset_path 'cate-astronomie.jpg' %>);
    align-items: center;
    justify-content: center;
    height: 300px;
    background-repeat: no-repeat;
    background-size: 100%;
    width: 100%;
    background-position-y: center;
    margin-bottom: 20px;
  }

  .col-md-3 {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .center-img {
    display:block;
    width: 100%;
    max-width: 300px;
    height: auto;
  }

</STYLE>

app/views/videos/new.html.erb
<div class="jumbotron new-video-jumbotron">
<h3 class="centered-text">Nouvelle Vidéo</h3>
</div>

<%= render 'videos-form' %>

<br><br><br><br>

<style>

.new-video-jumbotron {
  display: flex;
  background: url(<%= asset_path 'cate-sciences.jpg' %>);
  align-items: center;
  justify-content: center;
  height: 300px;
  background-repeat: no-repeat;
  background-size: 100%;
  width: 100%;
  background-position-y: center;
}

.centered-text {
  color: white;
  font-size: 60px;
  font-weight: 900;
  text-decoration:underline;
}

</style>

app/views/videos/show.html.erb
 
<div class="container">
  <div class="row">
    <div class="col-1">
    </div>

    <div class="col-10">
        <div class="video-clip">
            <div style="width:100%;">
                <%= video_tag(url_for(@video.clip), style:'width:100%;height:521px', controls:'') %>
            </div>
        </div>

        <div class ="video-title">
        <div class="d-flex justify-content-between">

            <div>
            <h3>"<%=@video.title %>"</h3>
            
            </div>
            

            <div>
            <% if (current_user && current_user.id == @video.user_id) || current_user.admin %>
                <%= link_to "Modifier", edit_video_path(@video.id), class: 'btn btn btn-warning'%>
                <%= link_to "Supprimer", video_path(@video.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn btn-danger'%>
                
            <% end %>
            </div>
        </div>
        </div>
        <hr>

        <div class ="video-infos">
            <p><strong> Catégorie</strong> : <%= @video.category.title %></p>
            <p><strong> Auteur</strong> : <%= @video.user.name %></p>
            <p><strong> Description</strong> : <%=@video.description %></p>
            <HR>
        </div>


        <div class ="video-comments">
            <%= render 'comments/comment' %>
        </div>


    </div>


    <div class="col-1">
    </div>
  </div>